repos:
  - repo: local
    hooks:
      - id: format
        name: ruff format
        entry: uv run ruff format backend
        language: system
        pass_filenames: false

      - id: lint
        name: ruff lint
        entry: uv run ruff check backend --fix
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: uv run mypy backend/app
        language: system
        pass_filenames: false
